### ISSUE TITLE
is this repo useful ?

### ISSUE THREAD

**Issue by Poltuu** [LuccaSA/luccasa.github.io#1]

**Comment by Poltuu** [comment]
@lucienbertin  ?

**Comment by lucienbertin** [comment]
yeah, its necessary if we wanna have a site available on the url `https://luccasa.github.io`. It hosts the websites of all public repos of luccasa, provided they have a branch `gh-pages`

https://pages.github.com/

the [lucca-ui](http://luccasa.github.io/lucca-ui/#/sass) demo page exist thanks to it

**Comment by jefBinomed** [comment]
Hi, nop, with @sanlucca we do an update in the demo of the last release of LuccaUI and in theory, this repo isn't mandatory anymore. 

We integrate the dependancies directly in the demo of LuccaUI. So except if you want to keep alive a demo of luccaUI 3 or less with a link to this repo, i think we don't need this one.

**Comment by lucienbertin** [comment]
see step 1 of the [guide](https://pages.github.com/), i think its mandator so that github knows that luccasa.github.io is active

then in matches luccasa.github.io/repo to the right repo on branch gh-pages and displays it

i dont mean it is necessary because of the content it hosts for the different demos (lucca-ui/lucca-front). i think its necessary for the page luccasa.github.io/lucca-ui to be resolved

**Comment by lucienbertin** [comment]
https://help.github.com/articles/user-organization-and-project-pages/

**Comment by lucienbertin** [comment]
![image](https://user-images.githubusercontent.com/10089239/36674216-b9896700-1b05-11e8-98ac-1ce2f03d6617.png)

@jefBinomed  put the demo for lucca-front under /docs
